app:
    resource: "@AppBundle/Controller/"
    type:     annotation
api_login_check:
    path: /api/login_check
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
user:
    resource: "@AppBundle/Controller/UserController.php"
    type:     rest
    prefix: /api
flat:
    resource: "@AppBundle/Controller/FlatController.php"
    type:     rest
    prefix: /api
widget:
    resource: "@AppBundle/Controller/WidgetController.php"
    type:     rest
    prefix: /api
todo:
    resource: "@AppBundle/Controller/TodoController.php"
    type:     rest
    prefix: /api
calender:
    resource: "@AppBundle/Controller/CalenderController.php"
    type:     rest
    prefix: /api
grocery:
    resource: "@AppBundle/Controller/GroceryController.php"
    type:     rest
    prefix: /api
